version: '3.3'
services:
 proxy:
  container_name: reverse-proxy
  image: nginx:1.21.6-alpine
  restart: always
  volumes:
   - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "80:80"
  networks:
   - oasip-nw

 database:
  container_name: db
  image: oasip-db-img
  build: ./db/.
  restart: always
  volumes:
   - type: bind
     source: ./db/my.cnf
     target: /etc/my.cnf
  ports:
   - "3306:3306"
  environment:
   MYSQL_ROOT_PASSWORD: "1111"
  networks:
   - oasip-nw

 backend:
  container_name: backend
  image: oasip-be-img
  build: ./INT221-nontonchao-backend/.
  restart: on-failure
  ports:
   - "8080:8080"
  depends_on:
   - database
  networks:
   - oasip-nw

 frontend:
  container_name: frontend
  image: oasip-fe-img
  build: ./INT221-nontonchao-frontend/.
  restart: on-failure
  volumes:
   - ./INT221-nontonchao-frontend/nginx.conf:/etc/nginx/conf.d/default.conf
  depends_on:
   - backend
  networks:
   - oasip-nw

networks:
 oasip-nw:
  