version: '3.3'
services:
 proxy:
  container_name: reverse-proxy
  image: nginx:1.21.6-alpine
  restart: always
  volumes:
   - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
   - /etc/ssl/oasipcert/intproj21.crt:/etc/ssl/oasipcert/intproj21.crt
   - /etc/ssl/oasipcert/privatekey.key:/etc/ssl/oasipcert/privatekey.key
  ports:
   - "80:80"
   - "443:443"
  networks:
   - oasip-nw

 database:
  container_name: db
  image: oasip-db-img
  build: ./db/.
  restart: always
  volumes:
   - type: bind
     source: ./db/my.cnf
     target: /etc/my.cnf
  volumes:
   - type: bind
     source: ~/oasip-data
     target: /var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: "1111"
  ports:
   - "3306:3306"
  networks:
   - oasip-nw

 backend:
  container_name: backend
  image: oasip-be-img
  build: ./INT221-nontonchao-backend/.
  restart: on-failure
  depends_on:
   - database
  volumes:
   - "~/files:/files"
  ports:
   - "8080:8080"
  environment:
   SPRING_APPLICATION_JSON: '{
    "spring.datasource.url"  : "jdbc:mysql://database:3306/oasip?allowPublicKeyRetrieval=true&useSSL=false",
    "spring.datasource.username" : "dev",
    "spring.datasource.password" : "0000",
    "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
    "spring.jpa.hibernate.ddl-auto" : "update"}'
  networks:
   - oasip-nw

 frontend:
  container_name: frontend
  image: oasip-fe-img
  build: ./INT221-nontonchao-frontend/.
  restart: on-failure
  volumes:
   - ./INT221-nontonchao-frontend/nginx.conf:/etc/nginx/conf.d/default.conf
  depends_on:
   - backend
  networks:
   - oasip-nw

networks:
 oasip-nw: